services:
  - type: web
    name: health-backend
    env: python
    rootDir: healthbackend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
